apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: e2e-fbc-releaseplanadmission
  namespace: managed-release-team-tenant
spec:
  origin: dev-release-team-tenant
  applications:
      - e2e-fbc-application
  data:
    fbc:
        fromIndex: quay.io/scoheb/fbc-index-testing:latest
        targetIndex: quay.io/scoheb/fbc-target-index-testing:latest
        binaryImage: registry.redhat.io/openshift4/ose-operator-registry:v4.12
        requestUpdateTimeout: 420
        buildTimeoutSeconds: 480
  pipelineRef:
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/fbc-release/fbc-release.yaml
    resolver: "git"
  policy: fbc-policy
  serviceAccount: release-service-account
