apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: rh-push-to-registry-redhat-iotest-component
  annotations:
    image.redhat.com/generate: 'true'
spec:
  application: rh-push-to-registry-redhat-iotest
  componentName: rh-push-to-registry-redhat-iotest-component
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
  source:
    git:
      context: ./
      devfileUrl: >-
        https://raw.githubusercontent.com/scoheb/devfile-sample-python-basic/main/devfile.yaml
      dockerfileUrl: >-
        https://raw.githubusercontent.com/scoheb/devfile-sample-python-basic/main/docker/Dockerfile
      url: 'https://github.com/scoheb/devfile-sample-python-basic'
  targetPort: 8081

