apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: rh-push-to-registry-redhat-io-test-rpa
  namespace: managed-release-team-tenant
spec:
  applications:
    - rh-push-to-registry-redhat-iotest
  origin: dev-release-team-tenant
  pipelineRef:
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/rh-push-to-registry-redhat-io/rh-push-to-registry-redhat-io.yaml
    resolver: "git"
  policy: rh-push-to-registry-redhat-io-test-policy
  serviceAccount: rh-push-to-registry-redhat-io-sa
  data:
    pyxis:
      server: stage
      secret: pyxis
    images:
      floatingTag: "rh-product-prefix"
      pushSourceContainer: false
    mapping:
      components:
        - name: rh-push-to-registry-redhat-iotest-component
          repository: quay.io/redhat-pending/rhtap----rh-push-to-registry-redhat-iotest-component
    sign:
      configMapName: hacbs-signing-pipeline-config-redhatrelease2
