apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: e2e-fbc-stage-index-releaseplanadmission
  namespace: managed-release-team-tenant
spec:
  origin: dev-release-team-tenant
  applications:
      - e2e-fbc-stage-index-application
  data:
    fbc:
        fromIndex: registry-proxy.engineering.redhat.com/rh-osbs/iib-pub-pending:v4.13
        targetIndex: ""
        binaryImage: registry.redhat.io/openshift4/ose-operator-registry:v4.12
        requestUpdateTimeout: 1000
        buildTimeoutSeconds: 1000
  pipelineRef:
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/fbc-release/fbc-release.yaml
    resolver: "git"
  policy: fbc-policy
  serviceAccount: release-service-account
